import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import { ScrollTrackerProvider } from '@/contexts/ScrollRectContext';
import { ThemeProvider } from '@/contexts/ThemeContext';

const quicksand = Quicksand({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} antialiased`}>
        <ScrollTrackerProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </ScrollTrackerProvider>
      </body>
    </html>
  );
}
